name = "kimpure/chalk_luau"
version = "0.1.6"
description = "Roblox/chalk-lua for Luau"
authors = ["Roblox", "kimpure"]
repository = "https://github.com/kimpure/chalk-luau"
license = "MIT"
includes = ["src/**", "README.md", "LICENSE.md", "pesde.toml"]

[target]
environment = "luau"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
darklua = { name = "pesde/darklua", version = "^0.16.0", target = "lune" }
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.28", target = "lune" }
